### ISSUE TITLE
GDPR compliance?

### ISSUE THREAD

**Issue by sebeichholz** [timonf/save-your-internet-widget#1]
Hey there,
thanks for your widget!

I am not sure if it is compliant with the GDPR (https://en.wikipedia.org/wiki/General_Data_Protection_Regulation), as the CDN (cdn.jsdelivr.net) seems to record personal data (ip addresses) from all users that visit a site that uses your widget.

I created a similar widget (https://github.com/sebeichholz/saveyourinternet) and I host it on my own server, which does *not* collect IP addresses (docker container with nginx and a special config that anonymizes ip addresses).

What now? :-(

PS: I do not want to complain in any way, I just want to inform you about the situation. I would be glad if you could prove that your used CDN is compliant to the GDPR.

**Comment by sebeichholz** [comment]
I might share my nginx-docker-config with you so that you can host the file yourself? Or we might do it together (I am using hetzner cloud). Let me know if you're interested (I am from Münster/Germany).

**Comment by timonf** [comment]
Hi @sebeichholz

Thanks for your engagement!! 

I asked the guys from blackout21.eu for hosting. I will update as soon as I'll get more information on it.

The file `dist/syi-widget.js` can also be downloaded and can be hosted everywhere. You can host it on your server, too :) This file contains all you need.

PS.: Nice to see other developers to work on something like this!

**Comment by timonf** [comment]
Hi @sebeichholz! There is also a version for European servers now: https://blackout21.eu/static/syi-widget.js

**Comment by sebeichholz** [comment]
Thanks! But if they do record IP addresses (in Europe) it's still a GDPR issue :-)

**Comment by NullDev** [comment]
Alternatively you could just disclose, that IP addresses are being logged by referencing JSDelivr's privacy policies: https://www.jsdelivr.com/privacy-policy-jsdelivr-net

**Comment by timonf** [comment]
@sebeichholz Then you can still upload it to your server! :) I will close this ticket now
